---
# tasks file for create_test_user
- name: Ensure group "rstudio-admins" exists
  group:
    name: rstudio-admins
    state: present

- name: Ensure group "rstudio-superuser-admins" exists
  group:
    name: rstudio-superuser-admins
    state: present

    


- name: Creating users test user without admin access
  user:
    name: test
    password: "{{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}"
    state: present
    shell: /bin/bash 
    createhome: yes 
    home: /home/test

- name: Creating users test2 user without admin access
  user:
    name: test2
    password: "{{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}"
    state: present
    shell: /bin/bash 
    createhome: yes 
    home: /home/test2

- name: Creating admin user
  user:
    name: admin
    password: "{{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}"
    state: present
    groups: rstudio-admins,rstudio-superuser-admins
    shell: /bin/bash 
    createhome: yes 
    home: /home/admin
