---
# tasks file for Rstudio
- name: Ensure Rstudio Server is installed
  yum:
    name: https://download2.rstudio.org/server/centos6/x86_64/rstudio-server-rhel-pro-1.2.5001-3-x86_64.rpm
    state: present

#- name: Deploy config for load balancing
#  template:
#    src: load-balancer
#    dest: /etc/rstudio/load-balancer

- name: Deploy cookie for load balancing
  template:
    mode: '0600'
    src: secure-cookie-key
    dest: /etc/rstudio/secure-cookie-key

- name: Deploy pem for launcher
  template:
    mode: '0600'
    src: launcher.pem
    dest:  /etc/rstudio/launcher.pem
    
- name: Deploy pub for launcher
  template:
    mode: '0600'
    src: launcher.pub
    dest:  /etc/rstudio/launcher.pub

- name: Deploy rserver.conf
  template:
    src: rserver.conf
    dest: /etc/rstudio/rserver.conf


- name: Deploy jupyter.conf
  template:
    src: jupyter.conf
    dest: /etc/rstudio/jupyter.conf

- name: Deploy launcher.conf
  template:
    src: launcher.conf
    dest: /etc/rstudio/launcher.conf


#- name: Deploy launcher-mounts
#  template:
#    src: launcher-mounts
#    dest: /etc/rstudio/launcher-mounts

- name: Retsart Rstudio
  service:
    name: rstudio-launcher
    state: restarted

- name: Retsart Rstudio
  service:
    name: rstudio-server
    state: restarted



